# Paths are mandatory and should be set to the correct location on your system
path_tmp: ''
path_dem: ''
path_inputs: [
  'path/to/precipitation',
  'path/to/temperature',
  'path/to/max_temperature',
  'path/to/min_temperature'
]
path_targets: [
  'path/to/precipitation',
  'path/to/temperature',
  'path/to/max_temperature',
  'path/to/min_temperature'
]

# RCMs to be used for bias correction and downscaling
RCMs: [
    'ALADIN63_CNRM-CM5',
    'ALADIN63_MPI-ESM-LR',
    'CCLM4-8-17_MIROC5',
    'CCLM4-8-17_MPI-ESM-LR',
    'RegCM4-6_CNRM-CM5',
    'RegCM4-6_MPI-ESM-LR',
    'REMO2015_MIROC5'
]

# Temporal selection for training/testing
date_start: '1971-01-01'
date_end: '2022-12-31'
years_train: [1971, 2000]
years_valid: [2001, 2010]
years_test: [2011, 2022]

# Temporal selection for using the models (bias correction and downscaling)
period_hist_start: '1971-01-01'  # Start of the historical period for bias correction
period_hist_end: '2019-12-31'  # End of the historical period for bias correction
period_proj_start: '2020-01-01'  # Start of the period of interest (e.g. future)
period_proj_end: '2089-12-31'  # End of the period of interest (e.g. future)

# Data properties
input_vars: ['tp', 't', 't_min', 't_max']
target_vars: ['tp', 't', 't_min', 't_max']
do_crop: False
crop_x: []
crop_y: []

# SBCK default bias correction method
bc_method: 'dOTC'

# All methods available in the package
bc_methods: [
    'QM',
    'QDM',
    'CDFt',
    'MRec',
    'ECBC',
    'MBCn',
    'QMrs',
    'R2D2',
    'AR2D2',
    'OTC',
    'dOTC',
    #'TSMBC',
    #'dTSMBC',
]

# Hyperparameters
lr: 0.0002
batch_size: 32
num_epochs: 100
