# Paths are mandatory and should be set to the correct location on your system
path_tmp: '/storage/workspaces/giub_hydro/hydro/data/tmp/pickle/files/'
path_dem: '/storage/workspaces/giub_hydro/hydro/data/SRTM/srtm_1k.tif'
path_inputs: [
  '/storage/workspaces/giub_hydro/hydro/data/RCM/regular-g0d11/precipitation/',
  '/storage/workspaces/giub_hydro/hydro/data/RCM/regular-g0d11/temperature/'
]
# path_inputs: [
#   '/storage/workspaces/giub_hydro/hydro/data/ERA5_Land/Switzerland-daily/precipitation/',
#   '/storage/workspaces/giub_hydro/hydro/data/ERA5_Land/Switzerland-daily/temperature/',
#   '/storage/workspaces/giub_hydro/hydro/data/ERA5_Land/Switzerland-daily/max_temperature/',
#   '/storage/workspaces/giub_hydro/hydro/data/ERA5_Land/Switzerland-daily/min_temperature/'
# ]
path_targets: [
  '/storage/workspaces/giub_hydro/hydro/data/MeteoSwiss/RhiresD_v2.0_swiss.lv95/',
  '/storage/workspaces/giub_hydro/hydro/data/MeteoSwiss/TabsD_v2.0_swiss.lv95/',
  '/storage/workspaces/giub_hydro/hydro/data/MeteoSwiss/TmaxD_v2.0_swiss.lv95/',
  '/storage/workspaces/giub_hydro/hydro/data/MeteoSwiss/TminD_v2.0_swiss.lv95/'
]




path_output: '/storage/workspaces/giub_hydro/hydro/data/tmp2/CDFt/'

# Temporal selection for training/testing
date_start: '1971-01-01'
date_end: '2022-12-31'
years_train: [1961, 2000]
years_valid: [2001, 2010]
years_test: [2011, 2022]


# Temporal selection for using the models (bias correction and downscaling)
period_hist_start: '1971-01-01'  # Start of the historical period for bias correction
period_hist_end: '2009-12-31'  # End of the historical period for bias correction
period_clim_start: '2010-01-01'  # Start of the period of interest (e.g. future)
period_clim_end: '2022-12-31'  # End of the period of interest (e.g. future)


#input_vars: ['pr', 'tas']
# target_vars: ['tp', 't']
input_vars: ['tp', 't']
target_vars: ['tp', 't']

do_crop: True
crop_x: [2700000, 2760000]
crop_y: [1190000, 1260000]
levels: [850, 1000]
resol_low: 0.1

# RCM
RCM: ['ALADIN63_CNRM-CM5','ALADIN63_MPI-ESM-LR','CCLM4-8-17_MIROC5','CCLM4-8-17_MPI-ESM-LR','RegCM4-6_CNRM-CM5','RegCM4-6_MPI-ESM-LR','REMO2015_MIROC5']

# QM
imputed_method: 'imputed_values' # or null to impute the NaN as zeros
# SBCK bias correction method
bias_correction_method: 'CDFt'
# hyperparams
n_channels_in: 5
n_channels_out: 2
input_size: [70, 60]
output_size: [70, 60]
learning_rate: 0.0002
batch_size: 32
num_epochs: 10
